# Generated by Django 4.0.5 on 2022-09-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_count_persons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="count_persons",
        ),
        migrations.AddField(
            model_name="order",
            name="count_tickets",
            field=models.PositiveSmallIntegerField(
                default=15, verbose_name="Count Tickets"
            ),
            preserve_default=False,
        ),
    ]
