# Generated by Django 4.0.5 on 2022-10-05 11:41

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def delete_orders(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tours", "0009_tour_max_passengers"),
        ("hotels", "0008_remove_roomreservation_room_and_more"),
        ("orders", "0004_remove_order_count_persons_order_count_tickets"),
    ]

    operations = [
        migrations.RunPython(delete_orders, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="orderroom",
            name="reservation",
        ),
        migrations.AddField(
            model_name="orderroom",
            name="end",
            field=models.DateTimeField(default=core.utils.one_day_hence),
        ),
        migrations.AddField(
            model_name="orderroom",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_rooms",
                to="tours.tourfeature",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderroom",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderroom",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_rooms",
                to="hotels.roomtype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderroom",
            name="start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="orderroom",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Successfully ordered"),
                    ("BOOKED", "Booked"),
                    ("FAULT", "Fault"),
                    ("CANCELED", "Canceled"),
                ],
                default="BOOKED",
                max_length=15,
                verbose_name="Status",
            ),
        ),
    ]
