version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./bookmaker/.env
  backend:
    build: ./bookmaker
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    volumes:
      - ./bookmaker:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - bookmaker/.env
    depends_on:
      - db

volumes:
  postgres_data:
