version: "3.9"

services:
  db:
    image: postgis/postgis
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./tour_agency/.env
  backend:
    build: ./tour_agency
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./tour_agency:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - tour_agency/.env
    depends_on:
      - db
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: on-failure
  celery:
    build: ./tour_agency
    command: celery -A tour_agency worker -B
    volumes:
      - ./tour_agency:/app/backend
    depends_on:
      - rabbitmq
      - backend
volumes:
  postgres_data:
