# Generated by Django 4.0.5 on 2022-06-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.UniqueConstraint(fields=('street', 'city'), name='uq_street_city'),
        ),
    ]
