# Generated by Django 4.0.5 on 2022-06-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_hotel_uq_street_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="image_url",
        ),
    ]
