# Generated by Django 4.0.5 on 2022-06-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0004_convenience_hotel_conveniences_roomtype_conveniences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roomtype",
            name="has_balcony",
        ),
        migrations.RemoveField(
            model_name="roomtype",
            name="has_own_bathroom",
        ),
    ]
