# Generated by Django 4.0.5 on 2022-06-28 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0005_remove_roomtype_has_balcony_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomtype",
            options={"verbose_name_plural": "Rooms"},
        ),
        migrations.AlterField(
            model_name="roomreservation",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rented_dates",
                to="hotels.roomtype",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="count_rooms",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="Count rooms"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="count_places",
            field=models.PositiveSmallIntegerField(
                default=2, verbose_name="Count places"
            ),
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
