# Generated by Django 4.0.5 on 2022-07-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_hotel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['cost_per_day'], 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AddField(
            model_name='roomtype',
            name='count_rooms',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Count rooms'),
        ),
    ]
