# Generated by Django 4.0.5 on 2022-06-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_roomtype_options_alter_roomreservation_room_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomreservation',
            name='exclude_overlapping_reservations',
        ),
    ]
