# Generated by Django 4.0.5 on 2022-10-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_convenience_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomreservation',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='user',
        ),
    ]
