# Generated by Django 4.0.5 on 2022-10-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_orderroom_reservation_orderroom_end_and_more"),
        ("hotels", "0008_remove_roomreservation_room_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RoomReservation",
        ),
    ]
