# Generated by Django 4.0.5 on 2022-06-05 10:18
import os

from django.db import migrations, models


def generate_superuser(apps, schema_editor):
    from users.models import User

    DJANGO_SU_EMAIL = os.getenv("DJANGO_SU_EMAIL", "admin@admin.com")
    DJANGO_SU_PASSWORD = os.getenv("DJANGO_SU_PASSWORD", "admin")

    User.objects.create_superuser(email=DJANGO_SU_EMAIL, password=DJANGO_SU_PASSWORD)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=256, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Is staff"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name_plural": "Users",
            },
        ),
        migrations.RunPython(generate_superuser),
    ]
