# Generated by Django 4.0.5 on 2022-10-03 18:39
import os
from django.db import migrations, models


def generate_superuser(apps, schema_editor):
    from users.models import User

    DJANGO_SU_EMAIL = os.getenv("DJANGO_SU_EMAIL", "admin@admin.com")
    DJANGO_SU_PASSWORD = os.getenv("DJANGO_SU_PASSWORD", "admin")

    User.objects.create_superuser(email=DJANGO_SU_EMAIL, password=DJANGO_SU_PASSWORD)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Is manager'),
        ),
        migrations.RunPython(generate_superuser),
    ]
