# Generated by Django 4.0.5 on 2022-07-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_onecitytour_price"),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MultiCityTourImage",
            new_name="TourImage",
        ),
        migrations.AlterModelOptions(
            name="tourimage",
            options={"verbose_name_plural": "TourImages"},
        ),
        migrations.DeleteModel(
            name="OneCityTourImage",
        ),
    ]
