# Generated by Django 4.0.5 on 2022-06-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_convenience_hotel_conveniences_roomtype_conveniences'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourfeature',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_features', to='hotels.hotel'),
        ),
    ]
