# Generated by Django 4.0.5 on 2022-06-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_remove_roomtype_has_balcony_and_more'),
        ('tours', '0002_alter_tourfeature_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourfeature',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_features', to='hotels.hotel'),
        ),
    ]
