# Generated by Django 4.0.5 on 2022-06-28 09:10

import core.utils
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0006_alter_roomtype_options_alter_roomreservation_room_and_more"),
        ("tours", "0003_alter_tourfeature_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="onecitytour",
            name="end",
            field=models.DateTimeField(
                default=core.utils.one_day_hence, verbose_name="End time"
            ),
        ),
        migrations.AddField(
            model_name="onecitytour",
            name="hotel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="one_city_tours",
                to="hotels.hotel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="onecitytour",
            name="start",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="From time"
            ),
        ),
        migrations.AlterField(
            model_name="tourfeature",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tour_features",
                to="hotels.hotel",
            ),
        ),
    ]
