# Generated by Django 4.0.5 on 2022-07-31 15:03

from django.db import migrations


def set_tour_features_order(apps, schema_editor):
    Tour = apps.get_model("tours", "Tour")
    for tour in Tour.objects.all().prefetch_related("tour_features"):
        tour.set_tourfeature_order(
            tour.tour_features.all().order_by("created").values_list("id", flat=True)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0007_alter_tourfeature_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tourfeature",
            options={"verbose_name_plural": "TourFeature"},
        ),
        migrations.AlterOrderWithRespectTo(
            name="tourfeature",
            order_with_respect_to="tour",
        ),
        migrations.RunPython(
            set_tour_features_order, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveConstraint(
            model_name="tourfeature",
            name="uq_tour_order",
        ),
        migrations.RemoveField(
            model_name="tourfeature",
            name="order",
        ),
    ]
