# Generated by Django 4.0.5 on 2022-08-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_tourfeature_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='max_passengers',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Max number of passengers'),
        ),
    ]
